export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const ADD_EVENT = 'ADD_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const CANCEL_EVENT = 'CANCEL_EVENT';
export const GET_EVENT = 'GET_EVENT';

export const EVENTS_DATA_LOADED = 'EVENTS_DATA_LOADED';
export const EVENTS_DATA_FETCHED = 'EVENTS_DATA_FETCHED';
export const CHANGE_ROOM_STATUS = 'CHANGE_ROOM_STATUS';
