export const GET_ALL_EVENTS = 'GET_ALL_EVENTS'
export const GET_ALL_EVENTS_START = 'GET_ALL_EVENTS_START'
export const GET_ALL_EVENTS_FINISH = 'GET_ALL_EVENTS_FINISH'
export const GET_ALL_EVENTS_ERROR = 'GET_ALL_EVENTS_ERROR'

export const ADD_EVENT = 'ADD_EVENT'
export const UPDATE_EVENT = 'UPDATE_EVENT'
export const CANCEL_EVENT = 'CANCEL_EVENT'
export const GET_EVENT = 'GET_EVENT'

export const FETCH_EVENTS_DATA = 'FETCH_EVENTS_DATA'
export const LOAD_EVENTS_DATA = 'LOAD_EVENTS_DATA'
export const CHANGE_ROOM_STATUS = 'CHANGE_ROOM_STATUS'
export const CHANGE_DRAWER_STATE = 'CHANGE_DRAWER_STATE'
