export const GET_RESERVATIONS = "GET_RESERVATIONS";
export const MAKE_RESERVATION = "MAKE_RESERVATION";
export const CALENDAR_DATA_LOADED = "CALENDAR_DATA_LOADED";
export const CALENDAR_DATA_FETCHED = "CALENDAR_DATA_FETCHED";
